55 create broccoli counter in the back
Picorims/app5-broccolii pull request #105
Opened 2024-12-27 00:03 UTC by Baryum

I added the PATCH route and updated the broccoli counter functions. Currently, the clicks only log (both in the clicker page's log and in the back's log), and no broccoli amount is actually computed. But the working PATCH route is a huge leap forward and adds to the completness of the app.

Arnaud helped me greatly by creating a debug page (DebugAddCards) allowing to add, equip and unequip cards to users, which will be required to test the broccoli counter functions.

2024-12-27 11:35 UTC, Picorims requested changes
SQL injection security flaw should be resolved.

2024-12-27 18:22 UTC, Baryum commented
@Picorims or @nano1342 could you resolve the last warning ? I don't want to make a mistake. Ty !

2024-12-27 20:17 UTC, nano1342 approved these changes

2024-12-28 11:28 UTC, Baryum commented
@Picorims

2024-12-28 12:34 UTC, Picorims approved these changes

2024-12-28 12:43 UTC, merged