Updated DbScript and created Class py file
Picorims/app5-broccolii pull request #38
Opened 2024-11-20 15:31 UTC by GaroshurlaTAMER

Updated database to fit the Card upgrade model (opposed to the Cookie Clicker model) Started to create classes following the database values, to create logics and prepare for the routes and results to send back.

2024-11-21 08:55 UTC, KFCSama submitted a review, later dismissed

2024-11-24 21:02 UTC, Picorims requested changes

2024-11-24 21:02 UTC, Picorims commented on src-back/sql_script.py
> +# %% Word list for each categories
I would move the lists in separate python files for better readability.

2024-12-20 11:56 UTC, Picorims approved these changes

2024-12-20 12:14 UTC, merged